use_frameworks!

target 'YHFCategoryKit_Example' do
  pod 'YHFCategoryKit', :path => '../'

  target 'YHFCategoryKit_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
